[project]
name = "react"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "crewai[tools]>=0.95.0",
    "environs>=14.1.0",
    "httpx>=0.28.1",
    "loguru>=0.7.3",
    "pydantic-ai>=0.0.19",
]
